/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package isdcontroller;

import isdmodeldao.DBManager;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

/**
 *
 * @author taylah
 */
public class ShowAllCustomersServlet extends HttpServlet {
    //doPost method allows the servlet to process data sent from Customer Information Management page and send back a response to the user
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        //create new HTTP session
        HttpSession session = request.getSession();
        //create connection to database to access customer records
        DBManager manager = (DBManager) session.getAttribute("manager");
        
        try {
            //set listOfCustomers as the ArrayList generated by the fetchCustomerList method
            request.setAttribute("listOfCustomers", manager.fetchCustomerList());
            request.getRequestDispatcher("customerInformationManagement.jsp").forward(request,response);
        } catch (SQLException ex) {
            //get information about error encountered in database
            ex.printStackTrace();
            System.out.println("SQLException error - Failed to retrieve Customers");
            //redirect user to Customer Information Management Page
            request.getRequestDispatcher("customerInformationManagement.jsp").forward(request, response);
        }
    }
}

